#!/usr/bin/env python3
"""Turn harness/spheres.json into an OpenSCAD data file for B7.

The values stay in the harness's glTF (Y-up) frame; B7_storm.scad maps them
with gltf_to_scad() so the axis convention lives in exactly one place.
"""
import json
import pathlib
import sys

src, dst = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
spheres = json.loads(src.read_text())
rows = ",\n".join(
    "    [%9.4f, %9.4f, %9.4f, %7.4f]" % (s["x"], s["y"], s["z"], s["r"])
    for s in spheres
)
dst.write_text(
    "// GENERATED by gen_spheres.py from harness/spheres.json -- do not edit.\n"
    "// %d spheres, [x, y, z, r] in the harness's glTF (Y-up) frame.\n"
    "SPHERES = [\n%s\n];\n" % (len(spheres), rows)
)
print(f"{dst}: {len(spheres)} spheres")
