/*
Copyright 2026 The Dice Table Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// CONTACT SHEETS (2i-F): every drive suite drops 20+ loose PNGs into
// tools/out/, which makes a run unreviewable at a glance and two runs
// incomparable. This stitches an index per directory: contact.html — a
// captioned thumbnail grid (click any cell for the full-size still) —
// plus a top-level index linking every sheet.
//
//   node tools/contact-sheet.mjs             # walk tools/out/ (default)
//   node tools/contact-sheet.mjs <dir> …     # only the named dirs
//
// Zero-dep, pure fs; safe to re-run (sheets are regenerated in place and
// live inside the gitignored out/ tree).

import { readdirSync, writeFileSync, statSync } from 'node:fs';
import { join, relative, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT_ROOT = join(fileURLToPath(new URL('.', import.meta.url)), 'out');

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');

function pngsIn(dir) {
  try {
    return readdirSync(dir).filter((f) => f.toLowerCase().endsWith('.png')).sort();
  } catch {
    return [];
  }
}

function subdirsIn(dir) {
  try {
    return readdirSync(dir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => join(dir, d.name))
      .sort();
  } catch {
    return [];
  }
}

function sheetHtml(title, pngs) {
  const cells = pngs.map((f) => `
    <figure>
      <a href="${esc(f)}" target="_blank"><img loading="lazy" src="${esc(f)}" alt="${esc(f)}"></a>
      <figcaption>${esc(f)}</figcaption>
    </figure>`).join('');
  return `<!DOCTYPE html>
<!-- generated by tools/contact-sheet.mjs — regenerate, never edit -->
<html lang="en"><head><meta charset="utf-8"><title>${esc(title)} — contact sheet</title>
<style>
  body { margin: 0; padding: 18px; background: #101214; color: #e8e2d2;
    font-family: system-ui, sans-serif; }
  h1 { font-size: 14px; letter-spacing: 0.08em; text-transform: uppercase; color: #99a1a9; }
  main { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 14px; }
  figure { margin: 0; border: 1px solid rgba(255,255,255,0.12); border-radius: 8px;
    padding: 8px; background: rgba(255,255,255,0.03); }
  img { width: 100%; height: auto; display: block; border-radius: 4px; background: #000; }
  figcaption { font-size: 11px; color: #99a1a9; margin-top: 6px; word-break: break-all;
    font-family: ui-monospace, monospace; }
</style></head>
<body><h1>${esc(title)} · ${pngs.length} stills</h1><main>${cells}</main></body></html>
`;
}

function indexHtml(entries) {
  const rows = entries.map(({ rel, n }) =>
    `<li><a href="${esc(rel ? `${rel}/contact.html` : 'contact.html')}">${esc(rel || '(top level)')}</a> · ${n} stills</li>`).join('\n');
  return `<!DOCTYPE html>
<!-- generated by tools/contact-sheet.mjs — regenerate, never edit -->
<html lang="en"><head><meta charset="utf-8"><title>drive-suite contact sheets</title>
<style>
  body { margin: 0; padding: 24px; background: #101214; color: #e8e2d2;
    font-family: system-ui, sans-serif; }
  a { color: #cdbe8a; }
  li { margin: 6px 0; font-size: 14px; }
</style></head>
<body><h1>Contact sheets</h1><ul>
${rows}
</ul></body></html>
`;
}

const args = process.argv.slice(2);
const roots = args.length ? args : [OUT_ROOT];
const made = [];

for (const root of roots) {
  let st = null;
  try { st = statSync(root); } catch { /* absent */ }
  if (!st || !st.isDirectory()) {
    console.error(`skip ${root}: not a directory`);
    continue;
  }
  const dirs = [root, ...subdirsIn(root)];
  for (const dir of dirs) {
    const pngs = pngsIn(dir);
    if (!pngs.length) continue;
    const title = dir === root ? basename(root) : relative(root, dir);
    writeFileSync(join(dir, 'contact.html'), sheetHtml(title, pngs));
    made.push({ dir, rel: dir === root ? '' : relative(root, dir), n: pngs.length });
    console.log(`${join(dir, 'contact.html')} (${pngs.length} stills)`);
  }
  if (root === OUT_ROOT && made.length) {
    writeFileSync(join(root, 'index.html'),
      indexHtml(made.filter((m) => m.dir.startsWith(root))));
    console.log(`${join(root, 'index.html')}`);
  }
}
if (!made.length) console.log('no PNGs found — nothing to stitch');
